"""create table

Revision ID: 17540e760640
Revises: ddf0d345bf5d
Create Date: 2023-01-03 18:03:38.130741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17540e760640'
down_revision = 'ddf0d345bf5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
